name: Generate, Upload, Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    environment:
      name: github-pages

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Node environment
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install Node dependencies
      - name: Install Node dependencies
        run: |
          npm install

      # Run Node script
      - name: Run Node script
        run: |
          node matf.js

      # Commit changes
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Add generated index.html

      # Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4